name: tablet_tower_flutter
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  connectivity: ^2.0.1
  csv: ^4.0.3
  cupertino_icons: ^0.1.3
  esys_flutter_share: ^1.0.2
  http: ^0.12.2
  share: ^0.6.5+2
  shared_preferences: ^0.5.8
  sqflite: ^1.3.1
  barcode_scan: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.8.0"
  flutter_native_splash: ^0.1.9

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/tablet_tower.png"
  adaptive_icon_background: "assets/tablet_tower.png"

flutter_native_splash:
  image: assets/tablet_tower.png
  color: "ffffff"
  android_disable_fullscreen: true

flutter:

  uses-material-design: true
  assets:
    - assets/